# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  issue_comment:                                     
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: ${{ github.event.issue.pull_request }}   # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
    - name: Support
      if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      run: |
        echo "PR: ${{ github.event.issue.pull_request.url }}"
    - name: test
      if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
      run: |
        echo "${{ github.event.comment.body }}"
  # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
